SELECT I.INI_BIP,
	   I.INI_ANNO,
	   I.INI_PROYECTO,
	   I.INI_MONTO,
	   P.PRO_ENERO,
	   P.PRO_FEBRERO,
	   P.PRO_MARZO,
	   P.PRO_ABRIL,
	   P.PRO_MAYO,
	   P.PRO_JUNIO,
	   P.PRO_JULIO,
	   P.PRO_AGOSTO,
	   P.PRO_SEPTIEMBRE,
	   P.PRO_OCTUBRE,
	   P.PRO_NOVIEMBRE,
	   P.PRO_DICIEMBRE,
	   E.ETA_NOMBRE,
	   F.FUE_NOMBRE,
	   T.UTEC_NOMBRE
FROM TMM_INICIATIVA I 
	INNER JOIN TMM_PROGRAMACION P   ON I.INI_ID = P.INI_ID
	INNER JOIN TMM_FUENTE F         ON I.FUE_ID = F.FUE_ID
	INNER JOIN TMM_ETAPA E          ON I.ETA_ID = E.ETA_ID
	INNER JOIN TMM_UNIDAD_TECNICA T ON I.UTEC_ID = T.UTEC_ID
ORDER BY I.INI_ID